name: ci

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Check black style
      uses: RojerGS/python-black-check@master
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Check Python lints
      uses: sunnysid3up/python-linter@master
