name: ci

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install Python linters
      run: pip install black isort flake8
    - name: Run Python linters
      uses: Gobot1234/lint-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Python linter selection
        black: true
        flake8: true
        isort: true
